name: Run main.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: '38 16 * * *' # At 16:38 UTC every day
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        run: python main.py
        
      - name: Fetch latest changes
        run: |
          git fetch origin
          git merge origin/main || true  # Prevents failure if there's nothing to merge

      - name: Commit files if there are changes
        run: |
          git config --local user.email "jebashinba2001@gmail.com "
          git config --local user.name "JebaShinba"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated logs" --allow-empty)
          
      - name: Push changes to the main branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

